---
- name: "Install unattended-upgrades."
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    cache_valid_time: "{{ unattended_cache_valid_time }}"
    update_cache: 'yes'

- name: "Create APT auto-upgrades Configuration."
  ansible.builtin.template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: "Create unattended-upgrades Configuration."
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
